spring.application.name=agenda

spring.datasource.url=jdbc:postgresql://localhost:5432/alpha_agenda
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080